---
- name: Shell Example
  hosts: test
  tasks: 

- name: stat yum
  stat: path=/etc/yum.repos.d
  register: /etc/yum.repos.d

- name: Backup yum.reposd
  command: mv /etc/yum.repos.d /etc/yum.repos.d.orig

- name: Make Yum directory
  command: mkdir /etc/yum.repos.d

